### PR TITLE
Boiler plate

### PR DESCRIPTION
**Pull request by briannakeune**
# Description

I saw some scripts I could add and a jest config. I'm not sure if there is any more boilerplate. 

The scripts were *test* and *server* so that start could run off of node, instead of nodemon. Nodemon is a dev dependency and will not make it into production.

I have to do some more research about configuring the coverage flag with code climate and jest, but I picked one from jest that will suffice for now.

What else are we planning to have in the auth folder? Or should the users folder be in there as well?

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by bgingrich** [comment]
The users folder could probably go in auth because it’s serving the same function essentially as auth-model and auth-router.

**Comment by briannakeune** [comment]
Should I move and edit that in this PR?

**Comment by bgingrich** [comment]
That works for me! Thank you!

**Comment by briannakeune** [comment]
I'll double-check everything and let y'all know when it's ready.

**Comment by briannakeune** [comment]
List of dependencies:
  "dependencies": {
    "axios": "^0.19.2",   **<--- Do we need this and node-fetch, or should we pick just one?**
    "bcryptjs": "^2.4.3",  ✔
    "body-parser": "^1.19.0", ✔
    "cors": "^2.8.5",   ✔
    "dotenv": "^6.1.0",    ✔
    "express": "^4.17.1",   ✔
    "express-session": "^1.15.6",   **<-- Do we still need this dependency?**
    "hbs": "^4.1.0",  ** <-- I googled this, and it seems interesting. I'd love to find out more. **
    "helmet": "^3.21.2", ✔
    "jsonwebtoken": "^8.5.1",    ✔
    "knex": "^0.20.8",    ✔
    "knex-cleaner": "^1.3.0",   ✔
    "node-fetch": "^2.6.0", **<-- Refer back to the axios dependency**
    "passport": "^0.4.1",    **<-- I know we might use these in the future??? Any info or is that decision documented any where?**
    "passport-facebook": "^3.0.0",
    "passport-google-oauth": "^2.0.0",
    "passport-google-oauth20": "^2.0.0",
    "pg": "^7.18.1",   ✔
    "pg-format": "^1.0.4",  **<-- Ooh what's this one being intended for?**
    "secret": "^1.0.2",    **<-- What's the plan with this one? It doesn't seemed used very often.**
    "sequelize": "^5.21.4",  **<-- Do we need this if we're using knex, and pg-format?**
    "standard": "^14.3.1"  ** <-- y'all have any linter rules that need to be documented?**
  },
  "devDependencies": {
    "@types/jest": "^25.1.1",  ** <-- curious why this was installed**
    "cross-env": "^7.0.0", ✔
    "jest": "^25.1.0", ✔
    "nodemon": "^2.0.2", ✔
    "supertest": "^4.0.2" ✔
  }

This line is in *server.js* and I was curious what **/docs** are going to show.

Also, I've noticed the *.env* file is on GitHub. So I'd recommend adding that to your gitignore files. Also if you have not please install [git-secrets](https://github.com/awslabs/git-secrets).

I don't know how y'all feel about loggers but [morgan](https://www.npmjs.com/package/morgan) is a pretty popular one.

That's all my opinions and questions today about this boilerplate.

**Comment by bgingrich** [comment]
My bad on not cleaning up the dependencies. Most were from trial and error from third party authentication.  I can go through and update and fix the other suggestions you had.

**Comment by briannakeune** [comment]
Awesome. I'll set up apiDocs then too since I'm here. :)
I'll also take out sequelize too.

**Comment by briannakeune** [comment]
I added some more commits. 

- I added the .env to the .gitignore 
- I installed apidoc and added a script. Anytime you create a documenting comment you can just run **npm run docs**
- I uninstalled node-fetch, secret, and sequelize

If any of those are a problem please let me know and I can update it. Other wise please feel free to merge this if you both agree.

**Pull request merged**
